---
AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: >
  EDA Day London 2024
  Patterns for building event-driven web and mobile app backends

Parameters:
  ProjectName:
    Description: Name for this project
    Type: String
    Default: patterns-eventdriven-frontends
  
  IoTCoreEndpoint:
    Description: IoT Core endpoint for account (DNS name only)
    Type: String

  WebPushPublicToken:
    Description: Public token for web push
    Type: String

  WebPushPrivateToken:
    Description: Private token for web push
    Type: String

Resources:
  Shared:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./shared/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        MaxSecondsToNextOrder: 90
        MaxWaitBetweenStatusChange: 60
  
  Pattern1:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/1-appsync/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
  
  Pattern2:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/2-eb-to-appsync/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  Pattern3:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/3-apigw-websocket/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  Pattern4:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/4-iot-core/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        IoTCoreEndpoint: !Ref IoTCoreEndpoint

  PushPattern:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/push/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        WebPushPublicToken: !Ref WebPushPublicToken
        WebPushPrivateToken: !Ref WebPushPrivateToken
  
  LongRunningPattern:
    Type: AWS::Serverless::Application
    DependsOn: Shared
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: ./patterns/long-running/template.yaml
      Parameters:
        ProjectName: !Ref ProjectName
  
Outputs:
  SharedRegion:
    Description: App config - region
    Value: !Ref AWS::Region
  
  SharedIdentityPoolId:
    Description: App config - identityPoolId
    Value: !GetAtt Shared.Outputs.IdentityPoolId
  
  SharedRestApiEndpoint:
    Description: App config - sharedEndpoint
    Value: !GetAtt Shared.Outputs.ApiEndpoint

  Pattern1GraphQLEndpoint:
    Description: App config - pattern1.endpoint
    Value: !GetAtt Pattern1.Outputs.GraphQLEndpoint

  Pattern2GraphQLEndpoint:
    Description: App config - pattern2.endpoint
    Value: !GetAtt Pattern2.Outputs.GraphQLEndpoint
  
  Pattern3WebSocketEndpoint:
    Description: App config - pattern3.endpoint
    Value: !GetAtt Pattern3.Outputs.WebSocketEndpoint
  
  Pattern4IoTEndpoint:
    Description: App config - mqttEndpoint
    Value: !Ref IoTCoreEndpoint
  
  PushApplicationServerKey:
    Description: App config - push.applicationServerKey
    Value: !Ref WebPushPublicToken
  
  LongRunningPatternGraphQLEndpoint:
    Description: App config - chat.endpoint
    Value: !GetAtt LongRunningPattern.Outputs.GraphQLEndpoint